[package]
name = "closure_test"
version = "0.1.0"
authors = ["viruscamp <viruscamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
closure = "0.3.0"
chrono = "0.4.19"