[workspace]

members = [
    "concurrent",
    "channel",
    "sync_send",
    "closure_test",
    "test_box_fn",
    "play",
    "http-server",
    "dead_lock",
    "reentrant_lock",
    "http-server-tokio",
    "http-server-async-std",
    "http-server-socket2",
]
