[package]
name = "http-server-socket2"
version = "0.1.0"
authors = ["viruscamp <viruscamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.0"
