[package]
name = "reentrant_lock"
version = "0.1.0"
authors = ["VirusCamp <viruscamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#thread_local = "1.1.3"
#lazy_static = "1.4.0"
lockfree = "0.5.1"
